name: scanner_zxing
description: Scanner implementation using Zxing
version: 1.0.0
publish_to: "none"

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  visibility_detector: 0.4.0+2
  scanner_shared:
    path: ../shared
  qr_code_scanner: 1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3
  openfoodfacts_flutter_lints:
    git: https://github.com/openfoodfacts/openfoodfacts_flutter_lints.git