name: data_importer_shared
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
