name: app_store_uri
description: App Store implementation based on an URI schemed
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  app_store_shared:
    path: ../shared

  url_launcher: 6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  openfoodfacts_flutter_lints:
    git:
      url: https://github.com/openfoodfacts/openfoodfacts_flutter_lints.git
      ref: flutter_3_24