name: smooth_ui_library
description: The official UI library for smooth_app.
version: 0.0.1

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
  flutter_lints: ^1.0.4
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  openfoodfacts: ^1.1.0-beta
# Uncomment those lines if you want to use a local version of the openfoodfacts package
#  openfoodfacts:
#    path: ../../../openfoodfacts-dart
  percent_indicator: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/product/
    - assets/icons/