name: app_store_shared
description: Shared interface between "App Store" implementations
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: "<3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  openfoodfacts_flutter_lints:
    git: https://github.com/openfoodfacts/openfoodfacts_flutter_lints.git

flutter: