name: smooth_app
description: A new official Open Food Facts application build with great user experience in mind.
version: 0.0.0
publish_to: "none"

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_lints: ^1.0.4
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.4
  device_preview: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_map: ^0.14.0
  flutter_widget_from_html_core: any
  fwfh_selectable_text: ^0.8.3
  flutter_secure_storage: ^5.0.2
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image_picker: ^0.8.4+11
  iso_countries: 2.1.0
  latlong2: ^0.8.1
  matomo_forever: ^1.0.0+1
  modal_bottom_sheet: ^2.0.1
  openfoodfacts: ^1.14.0
  #  openfoodfacts:
  #    path: ../../../openfoodfacts-dart
  package_info_plus: ^1.4.0
  permission_handler: ^9.2.0
  photo_view: ^0.13.0
  uuid: ^3.0.6
  provider: ^6.0.2
  qr_code_scanner: ^0.7.0
  rubber: ^1.0.1
  sentry_flutter: ^6.4.0 # careful with upgrading cf: https://github.com/openfoodfacts/smooth-app/issues/1300
  url_launcher: ^6.0.20
  visibility_detector: ^0.2.2
  camera: ^0.9.4+16
  percent_indicator: ^4.0.0
  mailto: ^2.0.0
  flutter_native_splash: ^2.1.1
  # Fork from cli1005 with iOS fix cf: https://github.com/openfoodfacts/smooth-app/issues/1155
  google_ml_barcode_scanner:
    git:
      url: https://github.com/cli1005/google_ml_barcode_scanner.git
      ref: master
  image_cropper: ^1.5.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  path: ^1.8.0 # careful with 1.8.1 because of https://github.com/flutter/flutter/issues/95478

# 'flutter pub run flutter_launcher_icons:main' to update
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app/smoothie-icon.1200x1200.png"
  adaptive_icon_background: "#00ccff"
  # Only the inner 72x72dp of the 108x108dp adaptive icon is shown
  # (extra padding of 18dp on all sides is used for visual effects)
  # https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
  adaptive_icon_foreground: "assets/app/smoothie-icon-transparent.android-adaptive.1080x1080.png"

# 'flutter pub run flutter_native_splash:create' to update
flutter_native_splash:
  image: assets/app/smoothie-icon-transparent.1200x1200.png
  color: "00ccff"
  image_dark: assets/app/smoothie-icon-transparent.1200x1200.png
  color_dark: "004455"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/actions/
    - assets/app/
    - assets/cache/
    - assets/categories/
    - assets/data/
    - assets/home/
    - assets/labels/
    - assets/metadata/
    - assets/misc/
    - assets/navigation/
    - assets/onboarding/
    - assets/product/
    - assets/ikonate_thin/
    - assets/ikonate_bold/
