name: smooth_app
description: A new official Open Food Facts application build with great user experience in mind.
version: 0.0.1+6
publish_to: "none"

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter_lints: ^1.0.4
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.4
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.0
  flutter_map: ^0.14.0
  flutter_widget_from_html_core: ^0.8.3+1
  flutter_secure_storage: ^5.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  iso_countries: 2.1.0
  latlong2: ^0.8.1
  matomo: ^1.1.0
  modal_bottom_sheet: ^2.0.0
  openfoodfacts: ^1.8.0
  # Uncomment those lines if you want to use a local version of the openfoodfacts package
#  openfoodfacts:
#    path: ../../../openfoodfacts-dart
  package_info_plus: ^1.3.0
  photo_view: ^0.13.0
  provider: ^6.0.1
  qr_code_scanner: ^0.6.1
  rubber: ^1.0.1
  sentry_flutter: ^6.2.2
  smooth_ui_library:
    path: ../smooth_ui_library
  url_launcher: ^6.0.17
  visibility_detector: ^0.2.2

  
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  path: ^1.8.0

dependency_overrides:
  path: ^1.8.0

# 'flutter pub run flutter_launcher_icons:main' to update
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app/smoothie-icon.1200x1200.png"
  adaptive_icon_background: "#00ccff"
  # Only the inner 72x72dp of the 108x108dp adaptive icon is shown
  # (extra padding of 18dp on all sides is used for visual effects)
  # https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
  adaptive_icon_foreground: "assets/app/smoothie-icon-transparent.android-adaptive.1080x1080.png"

# 'flutter pub run flutter_native_splash:create' to update
flutter_native_splash:
  image: assets/app/smoothie-icon-transparent.1200x1200.png
  color: "00ccff"
  image_dark: assets/app/smoothie-icon-transparent.1200x1200.png
  color_dark: "004455"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/actions/
    - assets/app/
    - assets/cache/
    - assets/categories/
    - assets/data/
    - assets/home/
    - assets/labels/
    - assets/metadata/
    - assets/misc/
    - assets/navigation/
    - assets/product/
    - assets/ikonate_thin/
    - assets/ikonate_bold/
