name: smooth_app
description: The next generation of the Open Food Facts mobile apps.
version: 0.0.0+734
publish_to: "none"

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: 7.0.2
  barcode_widget: 2.0.3
  carousel_slider: 4.2.1
  cupertino_icons: 1.0.5
  device_preview: 1.1.0
  flutter_svg: 2.0.5
  flutter_map: 2.2.0
  flutter_widget_from_html_core: 0.8.3+1
  fwfh_selectable_text: 0.8.3+1
  flutter_secure_storage: 5.1.2
  hive: 2.2.3
  hive_flutter: 1.1.0
  http: 0.13.5
  image_picker: 0.8.7
  iso_countries: 2.1.0
  latlong2: 0.8.1
  matomo_tracker: 2.0.0
  package_info_plus: 3.0.3
  device_info_plus: 8.1.0
  permission_handler: 10.2.0
  photo_view: 0.14.0
  uuid: 3.0.7
  provider: 6.0.5
  sentry_flutter: 6.22.0 # careful with upgrading cf: https://github.com/openfoodfacts/smooth-app/issues/1300
  sqflite: 2.2.5
  url_launcher: 6.1.3
  visibility_detector: 0.4.0+2
  assorted_layout_widgets: 7.0.0
  app_settings: 4.2.0
  diacritic: 0.1.3
  app_store_shared:
    path: ../app_store/shared
  audioplayers: 3.0.1
  percent_indicator: 4.2.3
  flutter_email_sender: 5.2.0
  flutter_native_splash: 2.2.19
  image: 4.0.16
  auto_size_text: 3.0.0
  crop_image: 1.0.6
  shared_preferences: 2.0.18
  intl: 0.17.0
  collection: 1.17.0
  path: 1.8.2
  path_provider: 2.0.13
  data_importer_shared:
    path: ../data_importer_shared
  data_importer:
    path: ../data_importer
  share_plus: 6.3.4
  fimber: 0.6.6
  shimmer: 2.0.0
  lottie: 2.2.0
  webview_flutter: 3.0.4
  flutter_custom_tabs: ^1.0.4
  flutter_image_compress: 1.1.3

  # According to the build variant, only one "app store" implementation must be added when building a release
  # Call "flutter pub remove xxxx" to remove unused dependencies
  app_store_apple_store:
    path: ../app_store/apple_app_store

  app_store_google_play:
    path: ../app_store/google_play

  app_store_uri:
    path: ../app_store/uri_store

  # We use two different scanning engines, 
  # mobile scanner powered by ML Kit for the Play Store and Apple App Store,
  # but qr_code_scanner which uses the open source ZXing for F-Droid
  camera: 0.10.5
  
  scanner_shared:
    path: ../scanner/shared

  scanner_ml_kit:
    path: ../scanner/ml_kit

  scanner_zxing:
    path: ../scanner/zxing




  openfoodfacts: 2.5.1
  # openfoodfacts:
  #   path: ../../../openfoodfacts-dart

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: 0.13.1
  flutter_test:
    sdk: flutter
  mockito: 5.3.2
  path_provider_platform_interface: 2.0.6
  plugin_platform_interface: 2.1.4
  flutter_lints: 2.0.1
  openfoodfacts_flutter_lints:
    git: https://github.com/openfoodfacts/openfoodfacts_flutter_lints.git

# 'flutter pub run flutter_launcher_icons:main' to update
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app/release_icon_transparent_1152x1152.png"
  adaptive_icon_background: "#FFFFFF"
  # Only the inner 72x72dp of the 108x108dp adaptive icon is shown
  # (extra padding of 18dp on all sides is used for visual effects)
  # https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
  adaptive_icon_foreground: "assets/app/release_icon_transparent_70pct_1152x1152.png"

# 'flutter pub run flutter_native_splash:create' to update
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#333333"
  #It must be a png file and should be sized for 4x pixel density.
  image: "assets/app/release_icon_transparent_1152x1152.png"

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. Currently, it is only supported for Android < v12 and iOS.
  # 200dp width and 80dp height.
  branding: assets/app/splashscreen_branding.png
  branding_dark: assets/app/splashscreen_branding_dark.png

  # https://developer.android.com/guide/topics/ui/splash-screen
  android_12:
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: "assets/app/release_icon_transparent_70pct_1152x1152.png"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#333333"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/app/
    - assets/audio/
    - assets/cache/
    - assets/cacheTintable/
    - assets/metadata/
    - assets/misc/
    - assets/network/cert.pem
    - assets/onboarding/
    - assets/packagings/
    - assets/preferences/
    - assets/product/
    - assets/icons/visor_icon.svg
