name: scanner_shared
description: Shared interface for the scanner implementations
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.10+1
  visibility_detector: 0.4.0+2
  provider: 6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  openfoodfacts_flutter_lints:
    git:
      url: https://github.com/openfoodfacts/openfoodfacts_flutter_lints.git
      ref: flutter_3_24

flutter: