name: scanner_mlkit
description: MLKit implementation for the scanning feature
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: "<3.3.0"

dependencies:
  flutter:
    sdk: flutter

  scanner_shared:
    path: ../shared

  flutter_isolate: 2.0.3
  google_mlkit_barcode_scanning: ^0.5.0
  typed_data: 1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  openfoodfacts_flutter_lints:
    git: https://github.com/openfoodfacts/openfoodfacts_flutter_lints.git

flutter: