name: Smoothie Google Play internal release

on:
  push:
    branches:
      - 'release/*'

jobs:
  test:
    name: Run Android testing
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Screenshots android tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: compileOffScreenshotsAndroidTestSources --stacktrace --info -PtestBuildType=screenshots

      - name: Unit tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: testObfDebugUnitTest testOffDebugUnitTest testOpfDebugUnitTest testOpffDebugUnitTest --stacktrace

  google-play-internal:
    needs: test
    name: Generate and deploy on Google Play
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Decrypt api json file
        run: cd ./fastlane/envfiles && ./decrypt_secrets.sh
        env:
          API_JSON_FILE_DECRYPTKEY: ${{ secrets.API_JSON_FILE_DECRYPTKEY }}
          STORE_JKS_DECRYPTKEY: ${{ secrets.STORE_JKS_DECRYPTKEY }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Workaround for Android Gradle plugin issue
        run: "echo \"ndk.dir=${ANDROID_HOME}/ndk-bundle\" > local.properties"

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install sentry-cli
        run: curl -sL https://sentry.io/get-cli/ | bash

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Run Fastlane release lane
        run: bundle exec fastlane release
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          CI_RELEASE: true
          SIGN_STORE_PATH: ../fastlane/envfiles/keystore.jks
          SIGN_STORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
          SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
          SIGN_KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}
