    name: GitHub Pages Deploy Action
    on:
        push:
            branches:
               - "develop"
               #- "dartdoc-smoothie"
    jobs:
        deploy-pages:
            name: Deploy to GitHub Pages
            runs-on: ubuntu-latest
            defaults:
              run:
                working-directory: ./packages/smooth_app
            steps:

            - name: Chekout code
              uses: actions/checkout@v3

            - name: Setup Flutter
              uses: actions/cache@v2
              with:
                path: ${{ runner.tool_cache }}/flutter
                key: flutter-2.5.0-stable
            - uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 2.5.0

            - name: Run Dartdoc
              run: pub global activate dartdoc && dartdoc
              
            - name: Deploy API documentation to Github Pages
              uses: JamesIves/github-pages-deploy-action@v4.2.5
              with:
                BRANCH: gh-pages
                FOLDER: packages/smooth_app/doc/api/
