name: App Store release

on:
  push:
    branches:
      - 'release/*'

jobs:
  testflight-release:
    name: Build and deploy to TestFlight testers
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Version
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0.2
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3.1.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: flutter2.10 #change this to force refresh cache
      - run: flutter --version

      - name: Get dependencies
        run: ci/pub_upgrade.sh
      
      - name: Bundle install
        run: cd ./packages/smooth_app/ios && gem install bundler:1.17.3 && bundle install

      - name: Decrypt iOS AuthKey file
        run: pwd && ls && cd ./packages/smooth_app/ios/fastlane/envfiles && ./decrypt_secrets.sh && ls
        env:
          AUTH_KEY_FILE_DECRYPTKEY: ${{ secrets.AUTH_KEY_FILE_DECRYPTKEY }}

      - name: Decrypt Android API JSON file
        run: cd ./packages/smooth_app/android/fastlane/envfiles && chmod +x ./decrypt_secrets.sh && ./decrypt_secrets.sh && ls
        env:
          API_JSON_FILE_DECRYPTKEY: ${{ secrets.API_JSON_FILE_DECRYPTKEY }}
          STORE_JKS_DECRYPTKEY: ${{ secrets.STORE_JKS_DECRYPTKEY }}

      # We are using the android version code here to have the version codes from iOS and android in sync 
      # in order for Sentry and other tools to work properly
      - name: Bump version
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: setVersion
          subdirectory: packages/smooth_app/android
        env:
          VERSION_NAME: ${{ env.RELEASE_VERSION }}

      - name: Build app
        run: cd ./packages/smooth_app && flutter build ios --release --no-codesign
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          PILOT_APPLE_ID: ${{ secrets.PILOT_APPLE_ID }}
          SPACESHIP_CONNECT_API_ISSUER_ID: ${{ secrets.SPACESHIP_CONNECT_API_ISSUER_ID }}
          SPACESHIP_CONNECT_API_KEY_ID: ${{ secrets.SPACESHIP_CONNECT_API_KEY_ID }}
          SPACESHIP_CONNECT_API_KEY_FILEPATH: ./fastlane/envfiles/AuthKey_KDAUTTM76R.p8
          CI_RELEASE: true

      - name: cat Podfile
        run: cd ./packages/smooth_app/ios && cat Podfile
 
      - name: Release ipa
        run: cd ./packages/smooth_app/ios && bundle exec fastlane beta
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          #FASTLANE_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          PILOT_APPLE_ID: ${{ secrets.PILOT_APPLE_ID }}
          SPACESHIP_CONNECT_API_ISSUER_ID: ${{ secrets.SPACESHIP_CONNECT_API_ISSUER_ID }}
          SPACESHIP_CONNECT_API_KEY_ID: ${{ secrets.SPACESHIP_CONNECT_API_KEY_ID }}
          SPACESHIP_CONNECT_API_KEY_FILEPATH: ./fastlane/envfiles/AuthKey_KDAUTTM76R.p8
          CI_RELEASE: true

