name: SmoothApp Post-Submit Tests

on: push
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.1.0
        with:
          distribution: 'zulu'
          java-version: 11
      
      # Setup flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: flutter2.10 #change this to force refresh cache
          
      - run: flutter --version
      
      # Get dependencies.
      - name: Get dependencies
        run: ci/pub_upgrade.sh

      # Check for formatting issues
      - name: Check for formatting issues (run "flutter format . ")
        run: flutter format --set-exit-if-changed .
      
      # analyze Dart for errors
      - name: Analyze code
        run: flutter analyze --fatal-infos --fatal-warnings .
      
      # Run tests
      - name: Run Tests with coverage
        run: ci/testing.sh
      
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
      
      # Build apk.
      - name: Build APK
        run: flutter build apk --debug
        working-directory: ./packages/smooth_app
      
      # Upload generated apk to the artifacts.
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: packages/smooth_app/build/app/outputs/flutter-apk/app-debug.apk
