name: SmoothApp Post-Submit Tests

on: 
  push:
    branches:
      - "develop"

env:
  FLUTTER_VERSION: '3.3.x'
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version: '3.0.5'
          #cache-key: flutter-${{ env.FLUTTER_VERSION }}-${{ hashFiles('**/pubspec.lock')}}
          cache-key: revert-3.0.5
        
      - run: flutter --version
      
      # Get dependencies.
      - name: Get dependencies
        run: ci/pub_upgrade.sh

      # Check for formatting issues
      - name: Check for formatting issues (run "flutter format . ")
        run: flutter format --set-exit-if-changed .
      
      # analyze Dart for errors
      - name: Analyze code
        run: flutter analyze --fatal-infos --fatal-warnings .
      
      # Run tests
      - name: Run Tests with coverage
        run: ci/testing.sh
            
      # Build apk.
      - name: Build APK
        run: flutter build apk --debug -t lib/entrypoints/android/main_google_play.dart
        working-directory: ./packages/app

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false

      # Upload generated apk to the artifacts.
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: packages/app/build/app/outputs/flutter-apk/app-debug.apk
