name: SmoothApp Post-Submit Tests

on: 
  push:
    branches:
      - "develop"
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'zulu'
          java-version: 17

      # Get the flutter version from ./flutter-version.txt
      - run: echo "FLUTTER_VERSION=$(cat flutter-version.txt)" >> $GITHUB_OUTPUT
        id: flutter-version

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          #channel: stable
          cache: true
          flutter-version: ${{ steps.flutter-version.outputs.FLUTTER_VERSION }}
          cache-key: flutter-${{ hashFiles('flutter-version.txt')}}-${{ hashFiles('packages\smooth_app\pubspec.lock')}}
        
      - run: flutter --version
      
      # Get dependencies.
      - name: Get dependencies
        run: ci/pub_upgrade.sh

      # Check for formatting issues
      - name: Check for formatting issues (run "dart format . ")
        run: dart format --set-exit-if-changed .
      
      # analyze Dart for errors
      - name: Analyze code
        run: flutter analyze --fatal-infos --fatal-warnings .
      
      # Run tests
      - name: Run Tests with coverage
        run: ci/testing.sh
            
      # Build apk.
      - name: Build APK
        run: flutter build apk --debug -t lib/entrypoints/android/main_google_play.dart
        working-directory: ./packages/smooth_app

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false

      # Upload generated apk to the artifacts.
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: packages/smooth_app/build/app/outputs/flutter-apk/app-debug.apk
