name: ðŸ¤³ðŸ¥« Open Food Facts mobile app Pre-Submit Tests

on:
  pull_request:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Analyze and test'

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: ðŸ“‚ Checkout code
        uses: actions/checkout@v4

      # Get the Flutter version from ./flutter-version.txt
      - run: echo "FLUTTER_VERSION=$(cat flutter-version.txt)" >> $GITHUB_OUTPUT
        id: flutter-version

      - name: ðŸªº Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          #channel: stable
          cache: true
          flutter-version: ${{ steps.flutter-version.outputs.FLUTTER_VERSION }}
          cache-key: flutter-${{ hashFiles('flutter-version.txt')}}-${{ hashFiles('packages\smooth_app\pubspec.lock')}}

      - run: flutter --version

      # Get dependencies
      - name: ðŸ“¦ Get dependencies
        run: ci/pub_upgrade.sh

      # Check for formatting issues
      - name: ðŸ§¹ Check for formatting issues (run "dart format . ")
        run: dart format --set-exit-if-changed .

      # Analyze Dart for errors
      - name: Analyze code
        run: flutter analyze --fatal-infos --fatal-warnings .

      # Run tests
      - name: ðŸ§ª Run Tests with coverage
        run: ci/testing.sh

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
