name: SmoothApp Pre-Submit Tests

on:
  pull_request:

env:
  FLUTTER_VERSION: '3.10.x'

jobs:
  build:
    name: 'Analyze and test'

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          #channel: stable
          cache: true
          flutter-version: '3.7.12'
          cache-key: current-stable

      - run: flutter --version

      # Get dependencies.
      - name: Get dependencies
        run: ci/pub_upgrade.sh

      # Check for formatting issues
      - name: Check for formatting issues (run "dart format . ")
        run: dart format --set-exit-if-changed .

      # analyze Dart for errors
      - name: Analyze code
        run: flutter analyze --fatal-infos --fatal-warnings .

      # Run tests
      - name: Run Tests with coverage
        run: ci/testing.sh

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
